### ISSUE TITLE
No terminal started

### ISSUE THREAD

**Issue by snuggles42** [iago-lito/intim#10]
Great tool. Installed successfully. Opened a Python-script and started an intim-session (,oi as suggested). But no terminal opens (tmux installed, added "let g:intim_terminal = "xterm"" to .vimrc). Message: ":call <SNR>16_LunchSession()". Disappears after some seconds.

**Comment by iago-lito** [comment]
Hello, and thank you for your interest in Intim :)

I can reproduce the behaviour you describe. The problem maybe comes from the fact that a naive call to `gnome-terminal` is non-blocking, as it spawns a new, independent terminal window, and returns the prompt. In contrast, a naive call to `xterm` *is* blocking and does not return the prompt, thus the hang you are experiencing.

I have fiddled a bit with messy `nohup` and `&` decorators to start addressing your problem in ff7795a. Vim hungs for approximately 30s on session launch, but the `xterm` window eventually opens correctly and Intim works as expected after that (unbearable) pause. 

Please try it and tell me if this works as a temporary workaround on your side. If not, I am afraid you'll have to try with another terminal emulator if you can, until we find another solution.

In any case: unexplained, systematic 30s lag on session launch is still unacceptable. I'll try to investigate into this next week-end.

Thank you for reporting :)

**Comment by iago-lito** [comment]
So your bug seems solved as you say [there](https://github.com/iago-lito/intim/commit/ff7795a85be6686aba0b177eeb91d6d7b3ea3f6e#commitcomment-32526290), but it's still lagging on my side. I'll keep this issue open as long as it looks unconsistent to me.

Out of curiosity, are you using classical `vim` or `neovim` or another  distribution like `gvim`, `onivim`, `vimgui` *etc.*?

**Comment by iago-lito** [comment]
Okay, got it. The 30s lag was due to a custom `postLaunch` command on my side. The problem is therefore fixed to me.
f8c5f63 documents the new `<tmux>` feature of `g:intim_terminal` so you can redefine your `xterm` invocation any way you prefer, as long as it works for you.  
Read more about it with `git pull` then `:help intim-terminal`.

Tell me if you need anything else, and happy Intim! :)

**Comment by snuggles42** [comment]
Classical vim 8.0.707

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
